### PR TITLE
refresh podpincher to work with k8s 1.5.x

### PR DESCRIPTION
**Pull request by spiffxp**
see individual commits for details

### CODE REVIEW

**Comment by coffeepac** [comment]
kraken-services isn't used anymore.  this work should, I think, be done over here:  https://github.com/samsung-cnct/k2-charts

**Comment by spiffxp** [comment]
@coffeepac agreed, just made the fix over there as well.... but I have a demo setup that doesn't use `helm` at all, and I'd rather not refactor that whole thing unless I have to

**Comment by coffeepac** [comment]
ahh, that's fair.  carry on sir.

**Comment by coffeepac** [comment]
LGTM

**Pull request merged**
