### PR TITLE
Update grafana/heapster/influxdb container versions to match latest

### PR DESCRIPTION
**Pull request by davidewatson**
versions used in the kubernetes source.

### CODE REVIEW

**Comment by davidewatson** [comment]
please retest this

**Comment by davidewatson** [comment]
please retest this

**Comment by davidewatson** [comment]
please retest this

**Comment by spiffxp** [comment]
can you rebase or recreate this such that your commit is the only one in this list?  a cherry-pick ontop of this repo's master ought to do the trick

**Comment by spiffxp** [comment]
lgtm

**Pull request merged**
